---
- name: Download Tomcat
  get_url: url={{tomcat_download_url}} dest={{tomcat_archive}}

- name: Unpack Tomcat archive
  unarchive: src={{tomcat_archive}} dest={{sdawebserver_home}} copy=no creates={{tomcat_home}}

- name: Config Tomcat server
  replace: dest={{tomcat_server_conf}}
           regexp="<Connector port=\"8009\" protocol=\"AJP/1.3\" redirectPort=\"8443\" />"
           replace="<Connector port=\"8009\" protocol=\"AJP/1.3\" redirectPort=\"8443\" tomcatAuthentication=\"false\" />"

- name: Fix ownership
  file: state=directory path={{tomcat_home}} owner={{sdawebserver_user}} group={{sdawebserver_user}} recurse=yes

- name: Start Tomcat
  environment:
    JAVA_HOME: "{{java_default}}"
  sudo: yes
  sudo_user: "{{sdawebserver_user}}"
  command: "nohup {{tomcat_home}}/bin/catalina.sh start"
