---
- name: Update httpd.conf 
  lineinfile: dest={{httpd_conf_file}} state=present backup=yes
              regexp="<VirtualHost *:80>\n Redirect permanent / https://{{inventory_hostname}}/ \n</VirtualHost>"
              line="<VirtualHost *:80>\n Redirect permanent / https://{{inventory_hostname}}/ \n</VirtualHost>"

- name: Update auth_kerb.conf
  lineinfile: dest={{mod_auth_kerb_conf_file}} state=present backup=yes
              regexp="<Location />\n SSLRequireSSL \n AuthType Kerberos \n AuthName \"IU Network ID\" \n KrbMethodNegotiate Off \n KrbAuthRealms ADS.IU.EDU \n KrbSaveCredentials On \n Krb5KeyTab /etc/httpd/conf/http.keytab \n require valid-user \n </Location>"
              line="<Location />\n SSLRequireSSL \n AuthType Kerberos \n AuthName \"IU Network ID\" \n KrbMethodNegotiate Off \n KrbAuthRealms ADS.IU.EDU \n KrbSaveCredentials On \n Krb5KeyTab /etc/httpd/conf/http.keytab \n require valid-user \n </Location>\n"

- name: Update ssl.conf
  lineinfile: dest={{mod_ssl_conf_file}} state=present backup=yes
              regexp="SSLProxyEngine on \nProxyPass     /sda ajp://localhost:8009/sda\nProxyPassReverse /sda ajp://localhost:8009/sda\n"
              line="SSLProxyEngine on \nProxyPass     /sda ajp://localhost:8009/sda\nProxyPassReverse /sda ajp://localhost:8009/sda\n"
              insertbefore="^</VirtualHost>"

- name: Copy over index.php and error.html
  template: src={{item}} dest="{{httpd_document_root}}/{{item}}" owner=apache group=apache mode=0644
